# Generators.py
# Low-level instruction generator definitions.
#
# "base_cost"  : cost of the FIRST purchase; each subsequent purchase
#                costs base_cost * 1.15^owned (cookie-clicker style scaling).
# "increment"  : base instructions/sec contributed per owned unit
#                (before any multipliers are applied).
#
# The "info" strings are displayed in the generator tooltip / info panel.
# They are designed as teaching aids: each one explains the real ARM64
# instruction (or pseudo-instruction), its x86-64 counterpart, and the
# KEY architectural difference a student must understand for the report.

GENERATORS = [
    {
        "name": "MOV",
        "label": "Buy MOV Unit",
        "base_cost": 10,
        "increment": 1,
        "info": (
            "MOV — Move / Register Copy\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Copy a value from one register to another.\n"
            "  No arithmetic performed — pure data transfer.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64) — RISC\n"
            "──────────────────────────────────────────\n"
            "  mov x0, x1          ; pseudo-instruction\n"
            "  ↳ assembled as: ORR x0, xzr, x1\n\n"
            "  mov x0, #42         ; immediate form\n"
            "  ↳ assembled as: MOVZ x0, #42\n\n"
            "  KEY FACTS:\n"
            "  • ARM64 has NO real MOV opcode for reg-to-reg.\n"
            "  • The assembler rewrites it using ORR with XZR.\n"
            "  • XZR = hard-wired zero register (always reads 0,\n"
            "    writes silently discarded).\n"
            "  • OR(value, 0) = value  →  clean copy, no extra HW.\n"
            "  • Separate opcodes for load (LDR) and store (STR).\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 (Intel/AMD) — CISC\n"
            "──────────────────────────────────────────\n"
            "  mov rax, rbx        ; reg → reg  (real opcode!)\n"
            "  mov rax, [rbx]      ; mem → reg  (load)\n"
            "  mov [rbx], rax      ; reg → mem  (store)\n"
            "  mov rax, 42         ; imm → reg\n\n"
            "  KEY FACTS:\n"
            "  • MOV is a REAL, dedicated opcode — one of x86's\n"
            "    most-used instructions.\n"
            "  • One mnemonic covers reg/mem/imm forms (overloaded).\n"
            "  • No zero register. Zero-out idiom:\n"
            "      xor rax, rax    ← preferred (no 64-bit immediate)\n"
            "      mov rax, 0      ← works but larger encoding\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → MOV is a pseudo-instruction (ORR + XZR alias).\n"
            "           Load = LDR, Store = STR  (separate opcodes).\n"
            "  x86-64 → MOV is a real opcode AND covers load+store.\n\n"
            "  RISC principle: simple, uniform instructions keep the\n"
            "  hardware decoder fast. CISC packs more work per opcode."
        ),
    },
    {
        "name": "ADD",
        "label": "Buy ADD Unit",
        "base_cost": 100,
        "increment": 5,
        "info": (
            "ADD — Integer Addition\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Add two values. Used in arithmetic, pointer math,\n"
            "  array indexing, and loop counters.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 (AArch64) — RISC\n"
            "──────────────────────────────────────────\n"
            "  add  x0, x1, x2          ; x0 = x1 + x2  (3 operands!)\n"
            "  add  x0, x1, #10         ; x0 = x1 + 10  (immediate)\n"
            "  adds x0, x1, x2          ; same + sets NZCV flags\n"
            "  add  x0, x1, x2, lsl #2  ; x0 = x1 + (x2 × 4)\n\n"
            "  KEY FACTS:\n"
            "  • THREE operands: destination is SEPARATE from sources.\n"
            "    x1 and x2 are never modified — non-destructive.\n"
            "  • Flags are NOT set by default (opt-in via 'S' suffix).\n"
            "  • Shifted-register form embeds a scale in one instruction:\n"
            "    add x0, base, idx, lsl #3  =  base + idx*8  (array!)\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 (Intel/AMD) — CISC\n"
            "──────────────────────────────────────────\n"
            "  add  rax, rbx            ; rax = rax + rbx  (2 operands)\n"
            "  add  rax, 10             ; rax = rax + 10\n"
            "  add  rax, [rbx]          ; rax += *rbx  (memory operand!)\n"
            "  lea  rax, [rbx + rcx*4]  ; rax = rbx + rcx*4  (scaled)\n\n"
            "  KEY FACTS:\n"
            "  • TWO operands: the LEFT is BOTH source AND destination.\n"
            "    It is always overwritten.\n"
            "  • Flags (CF ZF SF OF PF) ALWAYS set — no opt-out.\n"
            "  • Memory operands allowed directly in ADD.\n"
            "  • No built-in shift — LEA is the workaround for scaling.\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → 3 operands, non-destructive, opt-in flags,\n"
            "           built-in shift form.  Registers only.\n"
            "  x86-64 → 2 operands, destructive, flags always set,\n"
            "           memory operands allowed, uses LEA for scaling.\n\n"
            "  3-operand form = compilers can freely reuse sources\n"
            "  without spilling them to the stack first."
        ),
    },
    {
        "name": "IF_INST",
        "label": "Buy IF Unit",
        "base_cost": 500,
        "increment": 20,
        "info": (
            "Conditional Branch — compiled IF / ELSE\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Jump to a different code location depending on the\n"
            "  result of a prior comparison. This is the compiled\n"
            "  form of if / else logic.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 — HOW IF IS COMPILED\n"
            "──────────────────────────────────────────\n"
            "  ; if (a == b) { doTrue(); } else { doFalse(); }\n"
            "  cmp  x0, x1          ; subtract, set NZCV flags\n"
            "  b.ne else_label      ; NOT equal → go to else\n"
            "  bl   doTrue          ; true-body (falls through)\n"
            "  b    end_label\n"
            "else_label:\n"
            "  bl   doFalse\n"
            "end_label:\n\n"
            "  CONDITION SUFFIXES on one B opcode:\n"
            "  b.eq  b.ne  b.lt  b.gt  b.le  b.ge\n"
            "  b.lo  b.hi  b.ls  b.hs  (unsigned variants)\n\n"
            "  ZERO SHORTCUTS (no CMP needed!):\n"
            "  cbz  x0, label       ; if x0 == 0, branch\n"
            "  cbnz x0, label       ; if x0 != 0, branch\n"
            "  tbz  x0, #3, label   ; if bit 3 of x0 == 0, branch\n"
            "  tbnz x0, #3, label   ; if bit 3 of x0 != 0, branch\n\n"
            "  FLAGS register:  PSTATE  (NZCV bits)\n"
            "  N=Negative  Z=Zero  C=Carry  V=oVerflow\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 — HOW IF IS COMPILED\n"
            "──────────────────────────────────────────\n"
            "  cmp  rax, rbx        ; subtract, set EFLAGS\n"
            "  jne  else_label      ; NOT equal → jump to else\n"
            "  call doTrue\n"
            "  jmp  end_label\n"
            "else_label:\n"
            "  call doFalse\n"
            "end_label:\n\n"
            "  EACH CONDITION IS ITS OWN OPCODE:\n"
            "  je  jne  jl  jg  jle  jge\n"
            "  jb  ja   jbe jae  (unsigned variants)\n"
            "  jrcxz label  (jump if RCX == 0 — loop counter only)\n\n"
            "  FLAGS register:  EFLAGS  (32-bit)\n"
            "  ZF=Zero  SF=Sign  CF=Carry  OF=Overflow  PF=Parity…\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → ONE 'B' opcode + condition suffix.\n"
            "           CBZ/CBNZ/TBZ/TBNZ fold CMP+branch into 1 instr.\n"
            "           4 clean flag bits in PSTATE (NZCV).\n"
            "  x86-64 → Separate opcode per condition (je, jne, jl…).\n"
            "           No combined compare-and-branch shortcut.\n"
            "           6 flag bits + legacy PF/AF in EFLAGS.\n\n"
            "  Fewer mnemonics + CBZ shortcuts = tighter loops on ARM."
        ),
    },
    {
        "name": "LOAD_STORE",
        "label": "Buy LOAD/STORE Unit",
        "base_cost": 2_000,
        "increment": 80,
        "info": (
            "LOAD / STORE — Memory Access\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Transfer data between registers and memory.\n"
            "  In a RISC (ARM64) design these are the ONLY instructions\n"
            "  allowed to touch memory.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 — LDR / STR / LDP / STP\n"
            "──────────────────────────────────────────\n"
            "  ldr  x0, [x1]          ; x0 = *(int64_t*)x1\n"
            "  ldr  w0, [x1]          ; 32-bit load (zero-extends)\n"
            "  ldrsb x0, [x1]         ; 8-bit load, sign-extend to 64\n"
            "  str  x0, [x1]          ; *(int64_t*)x1 = x0\n"
            "  str  x0, [x1, #8]      ; store to x1 + 8\n"
            "  str  x0, [x1, x2, lsl #3] ; store to x1 + x2*8\n\n"
            "  PAIR transfers (key for function prologues!):\n"
            "  ldp  x0, x1, [sp]      ; load TWO regs in one instruction\n"
            "  stp  x29, x30, [sp, #-16]! ; save FP + LR, pre-decrement SP\n\n"
            "  RISC RULE: arithmetic ops (ADD, SUB…) work on REGISTERS\n"
            "  ONLY. You MUST load from memory first:\n"
            "    ldr x1, [x2]   ; get value\n"
            "    add x0, x0, x1 ; now add (two instructions total)\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 — MOV / MOVSX / MOVZX\n"
            "──────────────────────────────────────────\n"
            "  mov  rax, [rbx]        ; load 64-bit from address rbx\n"
            "  mov  eax, [rbx]        ; 32-bit load (zero-extends)\n"
            "  movsx rax, byte [rbx]  ; 8-bit load, sign-extend\n"
            "  mov  [rbx], rax        ; store rax → address rbx\n"
            "  mov  [rbx+8], rax      ; store to rbx + 8\n\n"
            "  CISC BONUS — arithmetic CAN read memory directly:\n"
            "  add  rax, [rbx]        ; rax += *rbx  (no LDR needed)\n"
            "  sub  rax, [rbx+rcx*8]  ; indexed memory arithmetic!\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → Load/Store ONLY access memory (RISC rule).\n"
            "           LDP/STP transfer PAIRS — 2 regs per instruction.\n"
            "           Arithmetic must use registers — more instructions,\n"
            "           but each is simple and fast to pipeline.\n"
            "  x86-64 → MOV covers both load AND store.\n"
            "           Arithmetic can take memory operands directly.\n"
            "           Fewer instructions, but each can be complex.\n\n"
            "  LDP/STP are a significant ARM advantage for function\n"
            "  call overhead — x86-64 needs 2 MOVs where ARM needs 1."
        ),
    },
    {
        "name": "CMP",
        "label": "Buy CMP Unit",
        "base_cost": 8_000,
        "increment": 300,
        "info": (
            "CMP — Compare (subtract-and-discard)\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Subtract two values, SET CPU flags based on the result,\n"
            "  then DISCARD the result. The flags are read by the next\n"
            "  conditional branch to make a decision.\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 — CMP / CMN / TST\n"
            "──────────────────────────────────────────\n"
            "  cmp  x0, x1          ; NZCV ← x0 - x1  (result discarded)\n"
            "  cmp  x0, #100        ; compare with immediate\n"
            "  cmn  x0, x1          ; NZCV ← x0 + x1  (compare negated)\n"
            "  tst  x0, x1          ; NZCV ← x0 AND x1 (bit-mask test)\n\n"
            "  CMP is a PSEUDO-INSTRUCTION:\n"
            "  cmp x0, x1  ≡  SUBS xzr, x0, x1\n"
            "  (Subtract with flag-Setting, store in XZR = discard)\n\n"
            "  TST is ALSO a pseudo-instruction:\n"
            "  tst x0, x1  ≡  ANDS xzr, x0, x1\n\n"
            "  FLAGS set:  PSTATE  NZCV\n"
            "  N = Negative  (result < 0)\n"
            "  Z = Zero      (result == 0)\n"
            "  C = Carry     (unsigned borrow)\n"
            "  V = oVerflow  (signed overflow)\n\n"
            "  ZERO-CHECK SHORTCUT — avoid CMP entirely:\n"
            "  cbz  x0, label       ; branch if x0 == 0  (no CMP!)\n"
            "  test rax, rax        ; (x86 idiom — see below)\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 — CMP / TEST\n"
            "──────────────────────────────────────────\n"
            "  cmp  rax, rbx        ; EFLAGS ← rax - rbx (discarded)\n"
            "  cmp  rax, 100        ; compare with immediate\n"
            "  test rax, rbx        ; EFLAGS ← rax AND rbx (bit test)\n"
            "  test rax, rax        ; canonical zero-check idiom\n\n"
            "  CMP IS A REAL OPCODE on x86-64 (not a pseudo).\n\n"
            "  WHY test rax, rax BEATS cmp rax, 0:\n"
            "  • Shorter encoding — no 64-bit zero immediate needed.\n"
            "  • CPUs recognise it as a dependency-breaking zero-check.\n\n"
            "  FLAGS set: EFLAGS (32-bit register)\n"
            "  ZF=Zero  SF=Sign  CF=Carry  OF=Overflow  PF=Parity  AF=Aux\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → CMP is a pseudo (SUBS + XZR). 4 clean flag bits.\n"
            "           CBZ/CBNZ skip CMP entirely for zero-checks.\n"
            "  x86-64 → CMP is a real opcode. 6 flag bits + legacy\n"
            "           PF/AF rarely used in modern code.\n"
            "           test rax, rax is the zero-check idiom.\n\n"
            "  ARM's leaner flag set reflects its newer, cleaner design;\n"
            "  x86's extra bits are legacy from the 8086 era (1978)."
        ),
    },
    {
        "name": "BRANCH",
        "label": "Buy BRANCH Unit",
        "base_cost": 30_000,
        "increment": 1_000,
        "info": (
            "BRANCH — Unconditional Jump & Function Call\n"
            "══════════════════════════════════════════\n\n"
            "PURPOSE:\n"
            "  Change the Program Counter to a new address — either\n"
            "  always (unconditional) or based on flags (conditional).\n"
            "  Also covers FUNCTION CALLS (branch-with-link / CALL).\n\n"
            "──────────────────────────────────────────\n"
            "ARM64 — B / BL / BR / BLR\n"
            "──────────────────────────────────────────\n"
            "  ; Unconditional:\n"
            "  b    label           ; PC = label  (±128 MB range)\n"
            "  br   x0              ; PC = x0  (register — unlimited range)\n\n"
            "  ; Function call (saves return address in X30 / LR):\n"
            "  bl   label           ; X30 = PC+4, PC = label  (±128 MB)\n"
            "  blr  x0              ; X30 = PC+4, PC = x0\n"
            "  ret                  ; PC = X30  (return)\n\n"
            "  ; Compare-and-branch (no CMP needed):\n"
            "  cbz  x0, label       ; if x0 == 0, branch\n"
            "  cbnz x0, label       ; if x0 != 0, branch\n"
            "  tbz  x0, #3, label   ; if bit 3 of x0 == 0, branch\n"
            "  tbnz x0, #3, label   ; if bit 3 of x0 != 0, branch\n\n"
            "  CALLING CONVENTION KEY POINTS:\n"
            "  • BL stores return address in X30 (Link Register / LR).\n"
            "  • Non-leaf functions MUST save X30 to the stack:\n"
            "      stp x29, x30, [sp, #-16]!  ; save FP + LR\n"
            "    Otherwise the NEXT bl overwrites X30 and you lose\n"
            "    the ability to return to your own caller!\n"
            "  • Arguments: X0–X7  (first 8 integer/pointer args)\n"
            "  • Return values: X0 (and X1 for 128-bit results)\n"
            "  • Stack: MUST be 16-byte aligned at every call.\n\n"
            "──────────────────────────────────────────\n"
            "x86-64 — JMP / CALL / RET\n"
            "──────────────────────────────────────────\n"
            "  ; Unconditional:\n"
            "  jmp  label           ; PC = label  (±2 GB range)\n"
            "  jmp  rax             ; PC = rax  (register)\n\n"
            "  ; Function call (return address pushed to STACK):\n"
            "  call label           ; push PC+len, PC = label\n"
            "  ret                  ; pop return address → PC\n\n"
            "  ; No compare-and-branch shortcut:\n"
            "  test rax, rax        ; 1. set flags\n"
            "  jz   label           ; 2. branch if zero  (always 2 instr)\n\n"
            "  CALLING CONVENTION KEY POINTS:\n"
            "  • CALL pushes return address on stack automatically.\n"
            "  • No link register — no need to save manually.\n"
            "  • Arguments (System V ABI, Linux/macOS):\n"
            "      RDI, RSI, RDX, RCX, R8, R9  (first 6 args)\n"
            "      Additional args pushed on stack.\n"
            "  • Return value: RAX (and RDX for 128-bit)\n"
            "  • Stack: 16-byte aligned BEFORE the call instruction.\n"
            "    (RSP % 16 == 8 inside callee — CALL pushed 8 bytes.)\n\n"
            "══════════════════════════════════════════\n"
            "KEY ARCHITECTURAL DIFFERENCE\n"
            "══════════════════════════════════════════\n"
            "  ARM64  → Return address in X30 (Link Register).\n"
            "           Compiler must save X30 for non-leaf functions.\n"
            "           CBZ/TBZ fold compare+branch into 1 instruction.\n"
            "           B range ±128 MB; indirect BR for anything farther.\n"
            "           8 argument registers (X0–X7).\n"
            "  x86-64 → Return address auto-pushed to stack by CALL.\n"
            "           Simpler nesting — no manual LR save needed.\n"
            "           No combined compare-and-branch shortcut.\n"
            "           JMP near range ±2 GB.\n"
            "           6 argument registers (RDI, RSI, RDX, RCX, R8, R9)."
        ),
    },
]